[advisories]
version = 2
unmaintained = "all"

[licenses]
version = 2
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "Unicode-3.0",
]
confidence-threshold = 1.0

[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true

[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
