[package]
name = "huginn-net-db"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
description = "P0f database parser and matching traits for network fingerprinting"
license = "MIT OR Apache-2.0"
authors = ["Maximiliano Biandratti"]
publish = false

[dependencies]
nom = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
lazy_static = "1.5.0"
