[package]
name = "huginn-net-db"
version = "1.0.0"
edition = "2021"
rust-version = "1.80"
description = "P0f database parser and matching traits for network fingerprinting"
license = "MIT OR Apache-2.0"
authors = ["Maximiliano Biandratti"]
repository = "https://github.com/biandratti/huginn-net"
keywords = ["p0f", "fingerprinting", "database", "network", "security"]
categories = ["network-programming", "parsing"]

[dependencies]
nom = "8.0.0"
thiserror = "2.0.14"
tracing = "0.1.41"
