[package]
name = "huginn-net-db"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
description = "P0f database parser and matching traits for network fingerprinting"
license = "MIT OR Apache-2.0"
authors = ["Maximiliano Biandratti"]
repository = "https://github.com/biandratti/huginn-net"
keywords = ["p0f", "fingerprinting", "database", "network", "security"]
categories = ["network-programming"]

[dependencies]
nom = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
