//! Golden PCAPs for UA vs observed-OS (`NAT_APP_UA`).
//!
//! Both captures are a Linux SYN (loopback) plus a Chrome-shaped HTTP/1.1 GET.
//! They differ only in the User-Agent OS token. Generated by
//! `scripts/capture-ua-os-pcaps.sh`.

use huginn_net::{Database, HuginnNet, ObservedOsScope, TcpMatchQuality, UaOsAgreement};
use huginn_net_http::output::{HttpRequestOutput, MatchQuality as HttpMatchQuality};
use std::path::Path;
use std::sync::mpsc;

const DIVERGENT: &str = "../pcap/ua-os-divergent-linux-syn-windows-ua.pcap";
const CONSISTENT: &str = "../pcap/ua-os-consistent-linux-syn-linux-ua.pcap";

fn collect_results(pcap_path: &str) -> Vec<huginn_net::output::FingerprintResult> {
    assert!(Path::new(pcap_path).exists(), "PCAP file must exist: {pcap_path}");
    let db = Database::load_default().unwrap_or_else(|e| panic!("load embedded p0f database: {e}"));
    let mut analyzer = HuginnNet::new(Some(&db), 1000, None)
        .unwrap_or_else(|e| panic!("construct HuginnNet: {e}"));
    let (tx, rx) = mpsc::channel();
    analyzer
        .analyze_pcap(pcap_path, tx, None)
        .unwrap_or_else(|e| panic!("analyze pcap {pcap_path}: {e}"));
    rx.into_iter().collect()
}

fn first_syn_os(results: &[huginn_net::output::FingerprintResult]) -> &str {
    let syn = results
        .iter()
        .find(|r| r.tcp_syn.is_some())
        .and_then(|r| r.tcp_syn.as_ref())
        .unwrap_or_else(|| panic!("expected a TCP SYN"));
    let os = syn
        .os_matched
        .os
        .as_ref()
        .unwrap_or_else(|| panic!("expected a SYN OS match, got {:?}", syn.os_matched.quality));
    assert!(
        matches!(syn.os_matched.quality, TcpMatchQuality::Matched { .. }),
        "SYN quality must be Matched, got {:?}",
        syn.os_matched.quality
    );
    os.name.as_str()
}

fn first_http_request(results: &[huginn_net::output::FingerprintResult]) -> &HttpRequestOutput {
    results
        .iter()
        .find(|r| r.http_request.is_some())
        .and_then(|r| r.http_request.as_ref())
        .unwrap_or_else(|| panic!("expected an HTTP request"))
}

fn assert_chrome_request(req: &HttpRequestOutput) {
    let browser = req
        .browser_matched
        .browser
        .as_ref()
        .unwrap_or_else(|| panic!("expected a Chrome HTTP match"));
    assert_eq!(browser.name, "Chrome", "browser name");
    assert!(
        browser.family.is_none(),
        "Chrome must be userland (no OS class), got {:?}",
        browser.family
    );
    assert!(
        matches!(req.browser_matched.quality, HttpMatchQuality::Matched(_)),
        "browser quality must be Matched, got {:?}",
        req.browser_matched.quality
    );
    assert!(
        !req.params.dishonest,
        "a Chrome-shaped UA must not trip params.dishonest, got {}",
        req.params
    );
}

#[test]
fn golden_divergent_windows_ua_on_linux_syn() {
    let results = collect_results(DIVERGENT);
    assert_eq!(first_syn_os(&results), "Linux");

    let req = first_http_request(&results);
    assert_chrome_request(req);
    let ua = req
        .sig
        .user_agent
        .as_deref()
        .unwrap_or_else(|| panic!("expected a User-Agent"));
    assert!(ua.contains("Windows NT"), "UA must claim Windows, got {ua}");
    assert_eq!(
        req.ua_os,
        UaOsAgreement::Divergent {
            ua_os: "Windows".to_owned(),
            network_os: "Linux".to_owned(),
            scope: ObservedOsScope::Flow,
        }
    );
}

#[test]
fn golden_consistent_linux_ua_on_linux_syn() {
    let results = collect_results(CONSISTENT);
    assert_eq!(first_syn_os(&results), "Linux");

    let req = first_http_request(&results);
    assert_chrome_request(req);
    let ua = req
        .sig
        .user_agent
        .as_deref()
        .unwrap_or_else(|| panic!("expected a User-Agent"));
    assert!(ua.contains("Linux"), "UA must claim Linux, got {ua}");
    assert_eq!(
        req.ua_os,
        UaOsAgreement::Consistent { os: "Linux".to_owned(), scope: ObservedOsScope::Flow }
    );
}
