name: Security audit

on:
  push:
    branches: [ "master" ]
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: read

jobs:
  cargo-deny:
    name: Cargo Deny (Workspace)
    permissions:
      checks: write
      contents: read
      issues: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: EmbarkStudios/cargo-deny-action@v2

  cargo-audit:
    name: Cargo Audit (Workspace)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: rustsec/audit-check@v2.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
