name: Advanced Security

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 2 * * 6'

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  cargo-geiger:
    name: Unsafe Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Install cargo-geiger
        run: cargo install cargo-geiger
      - name: Run unsafe code analysis
        run: cargo geiger --package ${{ github.event.repository.name }} --forbid-only

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause
